# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20190321_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='comment_date',
        ),
        migrations.AlterField(
            model_name='issue',
            name='username',
            field=models.CharField(default="User.objects.get('username')", max_length=30),
        ),
    ]
