# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20190322_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
