# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_auto_20190322_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion
                                    .CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
