# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-23 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20190322_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('username', models.CharField(max_length=20)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='issue',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion
                                    .CASCADE, to='issues.Issue'),
        ),
    ]
