# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-23 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_auto_20190323_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models
                                    .deletion.CASCADE, to='issues.Issue'),
        ),
    ]
