# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20190324_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
    ]
