# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_issue_num_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='num_comments',
            field=models.IntegerField(),
        ),
    ]
