# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_auto_20190325_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='num_comments',
        ),
    ]
