# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_auto_20190328_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='issues.Issue'),
        ),
    ]
