# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0014_auto_20190329_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion
                                    .CASCADE, to='issues.Issue'),
        ),
    ]
