# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190329_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/media/profile_images/default.png', upload_to='profile_images'),
        ),
    ]
