# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='12', on_delete=django.db.models
                                    .deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
